---
- name: "Validate role spec"
  validate_role_spec:
    spec: "interfaces_spec.yaml"

#- name: "Load interfaces"
#  include_role:
#    name: "ansible-network.config_manager"
#    tasks_from: "load.yaml"
#  vars:
#    config_manager_file: "interfaces.cfg.j2"

- name: "Load interfaces"
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: "config_manager/load.yaml"
  vars:
    config_manager_text: "{{ lookup( 'config_template', 'interfaces.cfg.j2') }}"


- name: "Save config"
  include_role:
    name: "ansible-network.config_manager"
    tasks_from: "save.yaml"