---
argument_spec:
  eos_mlag_config:
    type: dict
    options:
      name:
        aliases:
          - "interface"
        required: true
        description:
          - "Name of the interface to configure mlag"

      mlag:
        required: "true"
        description:
          - "The MLAG ID"

      group:
        type: dict
        options:
          id:
            required: true
            description:
              - "The Link Aggregation Group ID"

          mode:
            default: "active"
            choices:
              - "active"
              - "passive"
              - "on"
            description:
              - "LACP Mode: Active, Passive, ON"

          force:
            default: "no"
            description:
              - "Force channel association"
      
      extension:
        type: dict
        required: false
        description:
          - "Extension of specs with platform-specific keys/values"